name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: cd website && npm install && npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          publish-dir: website/build
